CC = gcc
CFLAGS = -Wall -Werror -Wextra 
CAT =cat.c
CHOOSE =choose.c
OPT= options.c
NAME =s21_cat

all:
	$(CC) $(CFLAGS) $(CAT) $(CHOOSE) $(OPT) -o $(NAME)

s21_cat:
	
	$(CC) $(CFLAGS) $(CAT) $(CHOOSE) $(OPT) -o $(NAME)

clean:
	rm -rf $(NAME)