CC = gcc
CFLAGS = -g -Wall -Werror -Wextra  
GREP =grep.c
OPT= flags_res.c

NAME =s21_grep

all:
	$(CC) $(CFLAGS) $(GREP)   $(OPT) -o $(NAME)

s21_grep:
	
	$(CC) $(CFLAGS) $(GREP)  $(OPT) -o $(NAME)

clean:
	rm -rf $(NAME)